# Generated by Django 6.0 on 2025-12-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=50)),
                ('matrix_json', models.TextField(blank=True, help_text='Matriz AHP 2x2 en JSON (opcional)', null=True)),
                ('weight_max', models.FloatField(default=0.7)),
                ('weight_freq', models.FloatField(default=0.3)),
                ('threshold_ppm', models.FloatField(default=0.0)),
                ('window_days', models.IntegerField(default=365)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='ahp_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ahp_score',
            field=models.FloatField(default=0.0),
        ),
    ]
