# Generated by Django 5.2.8 on 2025-12-02 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioAHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('peso', models.FloatField(default=1.0, help_text='Peso del criterio (0-1)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Criterio AHP',
                'verbose_name_plural': 'Criterios AHP',
                'ordering': ['-peso'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_total', models.FloatField(help_text='Puntuación AHP normalizada (0-100)')),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo Riesgo'), ('MEDIO', 'Medio Riesgo'), ('ALTO', 'Alto Riesgo'), ('CRITICO', 'Crítico')], max_length=20)),
                ('promedio_alcohol_ppm', models.FloatField()),
                ('maximo_alcohol_ppm', models.FloatField()),
                ('frecuencia_mediciones', models.IntegerField()),
                ('indice_variabilidad', models.FloatField()),
                ('fecha_analisis', models.DateTimeField(auto_now=True)),
                ('numero_muestras', models.IntegerField()),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación de Empleado',
                'verbose_name_plural': 'Calificaciones de Empleados',
                'ordering': ['-puntuacion_total'],
            },
        ),
    ]
