# Generated by Django 6.0 on 2025-12-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medidor', '0002_ahpconfig_empleado_ahp_last_updated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AHPConfig',
        ),
    ]
